# Configuration for TAE (Time-lagged Auto-encoder) baseline - CLN025
method: tae
molecule: CLN025
dataset_size: 50k
timelag: 10

# TAE specific parameters
mlcv_dim: 1
hidden_layers: [100, 100]
activation: tanh
dropout: [0.5, 0.5, 0.5]

# Training parameters
max_epochs: 1000
early_stopping_min_delta: 0.01
early_stopping_patience: 50

# Model save directory
model_save_dir: /home/shpark/prj-mlcv/lib/bioemu/model
