# Configuration for TAE (Time-lagged Auto-encoder) baseline
method: tae
molecule: 2F4K
dataset_size: 50k
timelag: 10
input_dim: 595

# TAE specific parameters
mlcv_dim: 1
hidden_layers: [100, 100]
activation: tanh
dropout: [0.5, 0.5, 0.5]

# Training parameters
max_epochs: 1000
early_stopping_min_delta: 0.01
early_stopping_patience: 50

# Plot
switch: False