# Configuration for TAE (Time-lagged Auto-encoder) baseline - CLN025
method: tica
molecule: 2F4K
dataset_size: 50k
timelag: 10
input_dim: 595

# TAE specific parameters
n_cvs: 1
activation: tanh
layers: [595, 100, 100, 1]

# Training parameters
max_epochs: 1000
early_stopping_min_delta: 0.01
early_stopping_patience: 50

# Plot
switch: False