_wandb:
    value:
        cli_version: 0.20.1
        m: []
        python_version: 3.10.18
        t:
            "1":
                - 1
                - 5
                - 50
                - 53
            "2":
                - 1
                - 5
                - 50
                - 53
            "3":
                - 16
                - 55
            "4": 3.10.18
            "5": 0.20.1
            "12": 0.20.1
            "13": linux-x86_64
feature:
    value:
        - alpha carbon distance
id:
    value: 1FME
lag:
    value: 5
simulation_id:
    value: 1
tica_dim:
    value: 2
